<!-- Delete button -->
<button
    id="mm-delete-button"
    title="<?= $block->escapeHtmlAttr(__('Delete')) ?>"
    type="button"
    class="action-secondary ui-button"
>
    <span class="ui-button-text">
        <span><?= $block->escapeHtml(__('Delete')) ?></span>
    </span>
</button>
<div id="mm-delete-confirmation">
    <div class="messages">
        <div class="message info">
            <span class="message-text">            
                <?= $block->escapeHtml(__('The sitemap XML file will also be deleted. Are you sure ?')) ?>
            </span>
        </div>
    </div>
</div>

<!-- Generate button -->
<button
    id="mm-generate-button"
    title="<?= $block->escapeHtmlAttr(__('Generate')) ?>"
    type="button"
    class="action-secondary ui-button"
>
    <span class="ui-button-text">
        <span><?= $block->escapeHtml(__('Generate')) ?></span>
    </span>
</button>
<div id="mm-generate-info">
    <div class="messages">
        <div class="message info">
            <span class="message-text">            
                <?= $block->escapeHtml(__('Please save the new sitemap first.')) ?>
            </span>
        </div>
    </div>
</div>

<script>
require([
    'jquery',
    'Naxero_MenuManager/js/sitemap/edit/form/buttons',
    'domReady!'
], function($, FormButtons) {
    // Set the form buttons events
    FormButtons.setEvents();
});
</script>
