<?php
    // Get the block data
    $config = $block->getData('config');
    $menuLinks = $block->getData('menu_links');
    $menuId = $block->getData('menu_id');
?>

<!-- Table buttons -->
<button type="button" id="mm-button-add">
    <?= $block->escapeHtml(__('Add')) ?>
</button>

<button type="button" id="mm-button-del">
    <?= $block->escapeHtml(__('Delete')) ?>
</button>

<button type="button" id="mm-button-generate">
    <?= $block->escapeHtml(__('Generate')) ?>
</button>

<div id="mm-tree-messages" class="messages mm-tree-messages">
</div>

<!-- Table placeholder -->
<div id="mm-tree">
    <form
        id="link-config-form-<?= $block->escapeHtmlAttr($menuId) ?>"
        name="link-config-form"
        enctype="multipart/form-data"
    >
    </form>
</div>

<!-- Generator form placeholder -->
<div id="mm-generator-form">
    <?= $block->escapeHtml($block->renderGeneratorForm()) ?>
</div>

<!-- Table handler script -->
<script>
    require([
        'jquery',
        'Naxero_MenuManager/js/menu/edit/form/fields/menu-links',
        'mage/backend/tabs',
        'domReady!'
    ], function($, MenuLinks) {
        // Menu links table
        MenuLinks.buildTable(
            <?= /* @noEscape */ json_encode($config) ?>,
            <?= /* @noEscape */ json_encode($menuLinks) ?>,
            <?= (int) $block->escapeHtml($menuId) ?>
        );
    });
</script>