<!-- Delete button -->
<button
    id="mm-delete-button"
    title="<?= $block->escapeHtmlAttr(__('Delete')) ?>"
    type="button"
    class="action-secondary ui-button"
>
    <span class="ui-button-text">
        <span><?= $block->escapeHtml(__('Delete')) ?></span>
    </span>
</button>

<div id="mm-delete-confirmation">
    <div class="messages">
        <div class="message info">
            <span class="message-text">            
                <?= $block->escapeHtml(__('Warning')) ?>
            </span>
        </div>
    </div>
    <p>            
        <?= $block->escapeHtml(__('Deleting this menu will also delete all related links.')) ?>
        <?= $block->escapeHtml(__('Do you wish to continue?')) ?>
    </p>
</div>

<script>
require([
    'jquery',
    'Naxero_MenuManager/js/menu/edit/form/buttons',
    'domReady!'
], function($, FormButtons) {
    // Set the form buttons events
    FormButtons.setEvents();
});
</script>
